In [1]:
import requests
import pandas as pd
import openpyxl

In [2]:
table = []
product = {}

In [3]:
for i in range(1,1000):
    url = "https://lifestyle-api.asiamiles.com/asiamilesspartacuswebservices/v2/asiamiles/search?fields=products(DEFAULT)%2Cfacets%2Cbreadcrumbs%2Cpagination(DEFAULT)%2Csorts(DEFAULT)%2CfreeTextSearch%2CcurrentQuery&query=%3Arelevance%3AallCategories%3At3_seasonal_yearend2023_foodnwine&currentPage={}&pageSize=9&categoryCode=t3_seasonal_yearend2023_foodnwine&sort=onlineDate-desc&lang=en&curr=MVR&country=HK".format(str(i))
    response = requests.get(url)
    response_json = response.json()
    if len(response_json['products']) != 0:
        for item in response_json['products']:
            for key in item:
                product[key] = item[key]
            table = table + [product]
            product = {}
    else:
        break

In [4]:
df = pd.DataFrame(table)

In [5]:
df

,baseOptions,baseProduct,brandCode,brandLogo,brandName,brandNameEn,cashConversionValue,cashOnly,categoryCodes,categoryNames,...,switchOffGroupA,termsAndconditions,url,validityPeriod,variantOptions,vedioType,vedioUrl,img2ForPLP,mpcDiscountFullCashPrice,variantPriceFromDisplay
0,[],IPA_0058,brand_theartisan,,The Artisan,,0.059187279142840,False,"[{'type': 'string', 'value': 'main_featuredpro...","[{'type': 'string', 'value': 'Cake & Confectio...",...,False,,/brands/The-Artisan/X%27mas-Delight-Combo-Gift...,,[],,,NaN,NaN,NaN
1,[],IPA_0054,brand_ipastry,,Imperial Patisserie,,0.052681992601324,False,"[{'type': 'string', 'value': 'main_featuredpro...","[{'type': 'string', 'value': 'Cake & Confectio...",...,False,,/brands/Imperial-Patisserie/X%27mas-Cookies-De...,,[],,,/medias/X-mas-Gift-Box-Mood-Shot.jpg-AML-Conve...,NaN,NaN
2,[],IPA_0055,brand_ipastry,,Imperial Patisserie,,0.059187279142840,False,"[{'type': 'string', 'value': 'main_featuredpro...","[{'type': 'string', 'value': 'Cake & Confectio...",...,False,,/brands/Imperial-Patisserie/X%27mas-Classic-Co...,,[],,,/medias/X-mas-Gift-Box-Mood-Shot.jpg-AML-Conve...,NaN,NaN
3,[],REA_0045,brand_reign,,REIGN,,0.060987667436928,False,"[{'type': 'string', 'value': 'main_featuredpro...","[{'type': 'string', 'value': 'Deli Food'}, {'t...",...,False,,/Lifestyle-Awards/Food-%26-Wine/Deli-Food/Sout...,,[],,,/medias/810-7841a.jpg-AML-Convert-294Wx195H?co...,1172,NaN
4,[],COM_0021,brand_comvita,,Comvita,,0.062500000160108,False,"[{'type': 'string', 'value': 'main_featuredpro...","[{'type': 'string', 'value': 'Lifestyle Awards...",...,False,,/Lifestyle-Awards/Food-%26-Wine/Pantry/Honey/U...,,[],,,NaN,431,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
248,[],RHI_0068,brand_regalriverside,,Regal Riverside Hotel,,0.057663628441164,False,"[{'type': 'string', 'value': 'main_featuredpro...","[{'type': 'string', 'value': 'Dining Out'}, {'...",...,False,,/Lifestyle-Awards/Food-%26-Wine/Dining-Out/Reg...,,[],,,NaN,348,NaN
249,[],RHI_0069,brand_regalriverside,,Regal Riverside Hotel,,0.061174642292460,False,"[{'type': 'string', 'value': 'main_featuredpro...","[{'type': 'string', 'value': 'Dining Out'}, {'...",...,False,,/Lifestyle-Awards/Food-%26-Wine/Dining-Out/Reg...,,[],,,NaN,551,NaN
250,[],PEN_0045,brand_thepeninsulaboutique,,The Peninsula Boutique,,0.048843187914816,False,"[{'type': 'string', 'value': 'main_featuredpro...","[{'type': 'string', 'value': 'Cake & Confectio...",...,False,,/Lifestyle-Awards/Food-%26-Wine/Cake-%26-Confe...,,[],,,NaN,NaN,NaN
251,[],IFC_0355,brand_teawg,,Tea WG,,0.065195587068880,False,"[{'type': 'string', 'value': 'main_featuredpro...","[{'type': 'string', 'value': 'Coffee & Tea'}, ...",...,False,,/brands/Tea-WG/-Cotton-Teabags-Collection---En...,,[],,,/medias/English-Breakfast-Tea1.jpg-AML-Convert...,NaN,NaN
252,[],COM_0013,brand_comvita,,Comvita,,0.076969332214728,False,"[{'type': 'string', 'value': 'main_featuredpro...","[{'type': 'string', 'value': 'May Joyful Offer...",...,False,,/brands/Comvita/UMF%E2%84%A2-15%2B-Manuka-Hone...,,[],,,/medias/Comvita-UMF15-12s-02.JPG-AML-Convert-2...,128,NaN

In [ ]:
countries = ["CDG","MXP","HND","TPE","ZRH","AMS"]
COUNTRIES = ["France","Italy","Japan","Taiwan","Switzerland","Netherlands"]

In [12]:
df = df[col ==['baseProduct', 'brandName', 'img2ForPLP', 'descr', 'discountFullCashPrice']]

NameError: name 'col' is not defined

In [7]:
df.to_excel("parsed_data/Food_and_Wines.xlsx")

In [ ]:
for item in response_json['products']:
    print(item['brandName'])