In [39]:
import pandas as pd
import random
from datetime import datetime, timedelta


middleware_df = pd.read_excel("/Users/orazkhankhaidar/Desktop/CathayGeniuses/cathay_api/Hackathon_Middleware_Bookings.xlsx")

In [40]:
countries_df = pd.read_excel("parsed_data/countries_codes.xlsx")

In [41]:
middleware_df

,Booking ID,Flight,From,To,Class,Name,Passenger ID,Segment ID
0,68BE5O,CX491,TPE,HKG,Y,SPENCE/LAWRENCE MR(ADT),510892B000014EBB,5009A2B00005D613
1,68EGEJ,CX491,TPE,HKG,Y,ASHLEY/MATTIE MISS(ADT),510812B00000C8DD,5009A2B00005E3D2
2,68JO8T,CX491,TPE,HKG,Y,WU/LONG MR(ADT),510892B000015B41,5009A2B00005F738
3,68DEVR,CX491,TPE,HKG,J,LI/WAI MAN MR(ADT),510892B00001515E,500A02B00006283D
4,NaN,CX491,TPE,HKG,J,WONG/KA WAI MISS(ADT),510892B000015206,500A02B00006283E
5,68EOJ6,CX259,HKG,LHR,Y,CHEUNG/TSZ WAH MR(ADT),510892B0000153AC,5009A2B00005E3F4
6,68FF2P,CX259,HKG,LHR,Y,LAM/KWOK FAI MR(ADT),510812B00000CADE,5009A2B00005E7EC
7,68K6BJ,CX259,HKG,LHR,J,ALLISON/CHLOE MS(ADT),510812B00000D1DE,500A02B000064390
8,68LIEJ,CX259,HKG,LHR,W,LEVY/MARVIN MR(ADT),510892B000015CB7,500A02B0000643B6
9,NaN,CX259,HKG,LHR,W,BENNETT/ELISABETH MS(ADT),510812B00000D2AF,500A02B0000643B7
10,NaN,CX259,HKG,LHR,W,LEVY/PATRICK MSTR(CHD/28MAY13),510812B00000D2D2,500A02B0000643B8
11,NaN,CX259,HKG,LHR,W,LEVY/ALEXANDRA MISS(CHD/09SEP16),510812B00000D2DD,500A02B0000643B9
12,68LIZG,CX491,TPE,HKG,Y,CHUNG/YAN CHING MR(ADT),510812B00000D429,500A02B000064AF1
13,NaN,CX259,HKG,LHR,Y,CHUNG/YAN CHING MR(ADT),510812B00000D429,5009A2B00005FDE8
14,68PJWH,CX491,TPE,HKG,J,KARNIK/RASHMI MS(ADT),5109C2B00001E932,500A02B0000658AB
15,NaN,CX259,HKG,LHR,J,KARNIK/RASHMI MS(ADT),5109C2B00001E932,5009A2B000060FF5
16,68NDOJ,CX491,TPE,HKG,J,FANG/JUNJIE MR(ADT),5109C2B00001E6BE,500A02B000064EFC
17,NaN,CX491,TPE,HKG,J,XIA/BINGWEN MS(ADT),510892B00001634B,500A02B000064EFD
18,NaN,CX491,TPE,HKG,J,FANG/LONGWEI MSTR(CHD/28AUG15),510892B00001637F,500A02B000064EFE
19,NaN,CX259,HKG,LHR,J,FANG/JUNJIE MR(ADT),5109C2B00001E6BE,5009A2B0000604C6
20,NaN,CX259,HKG,LHR,J,XIA/BINGWEN MS(ADT),510892B00001634B,5009A2B0000604C7
21,NaN,CX259,HKG,LHR,J,FANG/LONGWEI MSTR(CHD/28AUG15),510892B00001637F,5009A2B0000604C8

In [42]:
middleware_df['Passenger ID']

0     510892B000014EBB
1     510812B00000C8DD
2     510892B000015B41
3     510892B00001515E
4     510892B000015206
5     510892B0000153AC
6     510812B00000CADE
7     510812B00000D1DE
8     510892B000015CB7
9     510812B00000D2AF
10    510812B00000D2D2
11    510812B00000D2DD
12    510812B00000D429
13    510812B00000D429
14    5109C2B00001E932
15    5109C2B00001E932
16    5109C2B00001E6BE
17    510892B00001634B
18    510892B00001637F
19    5109C2B00001E6BE
20    510892B00001634B
21    510892B00001637F
Name: Passenger ID, dtype: object

In [43]:
dict = {}
table = []
now = datetime.now()
for item in middleware_df['Passenger ID']:
    random_number = random.randint(1,10)
    for i in range(random_number):
        dict['userId'] = item
        dict['destination'] = countries_df.code[random.randint(0,len(countries_df.index) - 1)]
        dict['sta'] = now - timedelta(seconds = random.randint(0,31536000))
        table += [dict]
        dict = {}

In [44]:
df = pd.DataFrame(table)

In [46]:
df.dtypes

userId                 object
destination            object
sta            datetime64[ns]
dtype: object

In [45]:
df.to_excel("parsed_data/user_destination.xlsx")

In [47]:
dic = {}
table1 = []
products_df = pd.read_excel("parsed_data/Food_and_Wines.xlsx")
products_df

,Unnamed: 0,baseProduct,brandName,img2ForPLP,description,discountFullCashPrice,countries,weight/kg,numberPurchased
0,1,IPA_0054,Imperial Patisserie,/medias/X-mas-Gift-Box-Mood-Shot.jpg-AML-Conve...,<p>Combo set includes Christmas Cookies (Green...,110,ZRH,4,42
1,2,IPA_0055,Imperial Patisserie,/medias/X-mas-Gift-Box-Mood-Shot.jpg-AML-Conve...,<p>Combo set includes Christmas Cookies (Green...,134,HND,5,19
2,3,REA_0045,REIGN,/medias/810-7841a.jpg-AML-Convert-294Wx195H?co...,<p>REIGN Abalone</p>\n<p>REIGN provides South ...,1260,TPE,5,10
3,6,RHI_0061,Regala Skycity Hotel,/medias/RGSH-Xmas-Dinner-Generic-2.jpg-AML-Con...,<p>Petra is an international cuisine restauran...,647,MXP,4,18
4,9,RHI_0062,Regala Skycity Hotel,/medias/RGSH-Xmas-Dinner-Generic-2.jpg-AML-Con...,<p>Petra is an international cuisine restauran...,801,TPE,2,38
...,...,...,...,...,...,...,...,...,...
80,242,COM_0004,Comvita,/medias/UMF20-2.JPG-AML-Convert-294Wx195H?cont...,<p>Comvita&trade; UMF&trade; 20+ Manuka Honey ...,974,TPE,4,47
81,243,COM_0003,Comvita,/medias/UMF-15-2.JPG-AML-Convert-294Wx195H?con...,<p>Comvita&trade; UMF&trade; 15+ Manuka Honey ...,562,MXP,1,7
82,245,CWS_0330,Fook Ming Tong,/medias/2011-Pu-Er-Tea-cake-02.jpg-AML-Convert...,<p>Fook Ming Tong 2011 Yunnan Pu Er Disc</p>\n...,966,HND,3,3
83,251,IFC_0355,Tea WG,/medias/English-Breakfast-Tea1.jpg-AML-Convert...,<p><strong>Tea WG Cotton Teabags Collection - ...,65,TPE,3,21
84,252,COM_0013,Comvita,/medias/Comvita-UMF15-12s-02.JPG-AML-Convert-2...,<p>UMF&trade; Manuka Honey benefits:</p>\n<p>R...,237,AMS,2,10

In [49]:
for item in middleware_df['Passenger ID']:
    random_number = random.randint(0,50)
    for i in range(random_number):
        dic['userId'] = item
        dic['itemId'] = products_df.baseProduct[random.randint(0,len(products_df.index) - 1)]
        dic['purchaseTime'] = now - timedelta(seconds = random.randint(0,31536000))
        dic['numPurchased'] = random.randint(0,20)
        table1 += [dic]
        dic = {}
df1 = pd.DataFrame(table1)

In [51]:
df1.to_excel("parsed_data/users_purchase_history.xlsx")